# Funding options for the project
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: [host-uk]

# Other platforms (uncomment and configure as needed)
# patreon: username
# open_collective: project-name
# ko_fi: username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: username
# issuehunt: username
# otechie: username
# lfx_crowdfunding: project-name

# Custom funding URLs (up to 4)
custom:
  - https://btcpayserver.org/donate/
